sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
  localoss:
    dir-path: D:\Projects\skytakeaway\resources
  redis:
    host: localhost
    port: 6379
    database: 0
  wechat:
    appid:
    secret:
    mchid: example
    mchSerialNo: example
    privateKeyFilePath: example
    apiV3Key: example
    weChatPayCertFilePath: example
    notifyUrl: example
    refundNotifyUrl: example
  shop:
    address: 北京市海淀区成府路28号
  baidu:
    ak: SI6agxvAjTmHijRYXyymDRVG6qKxtf79
